# Generated by Django 4.2.3 on 2023-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scores',
            field=models.TextField(default='{"action": 0, "adventure": 0, "comedy": 0, "fantasy": 0, "mystery": 0, "science fiction": 0, "fairy tale": 0, "animal": 0, "educational": 0, "historical": 0}'),
        ),
    ]
