# Generated by Django 4.2.3 on 2023-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_story_content_alter_userprofile_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
