# Generated by Django 4.1.4 on 2023-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('age_range', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('story_type', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('science_fiction', 'Science Fiction'), ('fairy_tale', 'Fairy Tale'), ('animal', 'Animal'), ('educational', 'Educational'), ('historical', 'Historical')], max_length=20)),
                ('picture', models.ImageField(upload_to='story_pictures')),
                ('length_minutes', models.PositiveIntegerField(choices=[(1, '1 minute'), (2, '2 minutes'), (5, '5 minutes'), (10, '10 minutes')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scores',
            field=models.TextField(default='{"action": 0, "adventure": 0, "comedy": 0, "fantasy": 0, "mystery": 0, "science_fiction": 0, "fairy_tale": 0, "animal": 0, "educational": 0, "historical": 0}'),
        ),
    ]
