# Generated by Django 4.1.4 on 2023-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_story_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], max_length=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='picture',
            field=models.ImageField(default=None, upload_to='story_pictures'),
        ),
    ]
