# Generated by Django 4.1.4 on 2023-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_story_gender_alter_story_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileimg',
            field=models.CharField(choices=[('img1', 'Image 1'), ('img2', 'Image 2'), ('img3', 'Image 3'), ('img4', 'Image 4')], default='img0', max_length=10),
        ),
    ]
