# Generated by Django 4.1.4 on 2023-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_story_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/audio_files'),
        ),
    ]
